const data = [
  {
    asin: "B0CWHXVLXG",
    product_title:
      "Moto G 5G | 2024 | Unlocked | Made for US 4/128GB | 50MP Camera | Sage Green",
    product_price: "$149.99",
    product_original_price: "$199.99",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 1411,
    product_url: "https://www.amazon.com/dp/B0CWHXVLXG",
    product_photo:
      "https://m.media-amazon.com/images/I/71Sbx9zQN3L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "$106.64",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: true,
  },
  {
    asin: "B0CTW8TXGH",
    product_title:
      "Tracfone | Motorola Moto g Play 2024 | Locked | 64GB | 5000mAh Battery | 50MP Quad Pixel Camera | 6.5-in. HD+ 90Hz Display | Sapphire Blue",
    product_price: "$39.88",
    product_original_price: "$49.99",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 248,
    product_url: "https://www.amazon.com/dp/B0CTW8TXGH",
    product_photo:
      "https://m.media-amazon.com/images/I/71CxUvG46rL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$39.88",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Wed, Jan 29",
    has_variations: false,
  },
  {
    asin: "B0D7HV2PC9",
    product_title:
      "Google Pixel 9 - Unlocked Android Smartphone with Gemini, 24-Hour Battery, Advanced Camera, and 6.3&quot; Actua Display - Peony - 128 GB",
    product_price: "$649.00",
    product_original_price: "$799.00",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 251,
    product_url: "https://www.amazon.com/dp/B0D7HV2PC9",
    product_photo:
      "https://m.media-amazon.com/images/I/71xYvFHoSuL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "$615.37",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Wed, Jan 29",
    has_variations: true,
  },
  {
    asin: "B0CYQ916ZY",
    product_title:
      "Google Pixel 8a - Unlocked Android Phone with Google AI, Advanced Pixel Camera and 24-Hour Battery - Obsidian - 128 GB",
    product_price: "$399.00",
    product_original_price: "$499.00",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 903,
    product_url: "https://www.amazon.com/dp/B0CYQ916ZY",
    product_photo:
      "https://m.media-amazon.com/images/I/71n1Bn04lJL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "$383.04",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: true,
  },
  {
    asin: "B0CSB22F9C",
    product_title:
      "Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
    product_price: "$149.99",
    product_original_price: "$167.00",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 1438,
    product_url: "https://www.amazon.com/dp/B0CSB22F9C",
    product_photo:
      "https://m.media-amazon.com/images/I/31bNhi6E3eL._AC_UY650_FMwebp_QL65_.jpg",
    product_num_offers: 12,
    product_minimum_offer_price: "$149.50",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "4K+ bought in past month",
    delivery: "FREE delivery",
    has_variations: false,
  },
  {
    asin: "B0BZG14KFJ",
    product_title:
      "Panasonic Cordless Phone with Answering Machine, Advanced Call Block, Bilingual Caller ID and Easy to Read High-Contrast Display, Expandable System with 2 Handsets - KX-TGD832M (Metallic Black)",
    product_price: "$59.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 4912,
    product_url: "https://www.amazon.com/dp/B0BZG14KFJ",
    product_photo:
      "https://m.media-amazon.com/images/I/81nkYlfA5ZL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "$20.58",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: false,
  },
  {
    asin: "B086QCGQ8C",
    product_title:
      "AT&amp;T BL102-3 DECT 6.0 3-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black",
    product_price: "$78.95",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 28262,
    product_url: "https://www.amazon.com/dp/B086QCGQ8C",
    product_photo:
      "https://m.media-amazon.com/images/I/81xDumBYGBL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "$34.85",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: false,
    product_badge: "Best Seller",
  },
  {
    asin: "B0CRWT7WF1",
    product_title:
      "Samsung Galaxy A05 A055M 64GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Black",
    product_price: "$87.94",
    product_original_price: "$94.49",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 353,
    product_url: "https://www.amazon.com/dp/B0CRWT7WF1",
    product_photo:
      "https://m.media-amazon.com/images/I/61UjBLFlH2L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$87.94",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Wed, Jan 29",
    has_variations: true,
  },
  {
    asin: "B0DLHNWHRF",
    product_title:
      "SAMSUNG Galaxy A16 5G A Series Cell Phone, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, US Version, 2025, Blue Black",
    product_price: "$199.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 32,
    product_url: "https://www.amazon.com/dp/B0DLHNWHRF",
    product_photo:
      "https://m.media-amazon.com/images/I/71KGkQ+KOKL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "$191.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: true,
  },
  {
    asin: "B0CJCTW1C5",
    product_title:
      "Nokia C2 2E | Android 11 (Go Edition) | Unlocked Smartphone | All Day Battery | 2/32GB | 5.7-Inch Screen | International Version | Blue",
    product_price: "$59.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.3",
    product_num_ratings: 210,
    product_url: "https://www.amazon.com/dp/B0CJCTW1C5",
    product_photo:
      "https://m.media-amazon.com/images/I/71PGVVHz08L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "$49.63",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: false,
  },
  {
    asin: "B09LNX6KQS",
    product_title: "Apple iPhone 13, 128GB, Blue - Unlocked (Renewed)",
    product_price: "$354.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 14018,
    product_url: "https://www.amazon.com/dp/B09LNX6KQS",
    product_photo:
      "https://m.media-amazon.com/images/I/71MKNCEgE6L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 57,
    product_minimum_offer_price: "$294.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    product_availability: "Only 3 left in stock - order soon.",
    climate_pledge_friendly: true,
    sales_volume: "1K+ bought in past month",
    delivery:
      "FREE delivery Fri, Jan 31 Or fastest delivery Thu, Jan 30 Only 3 left in stock - order soon.",
    has_variations: true,
  },
  {
    asin: "B08PP5MSVB",
    product_title: "Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)",
    product_price: "$247.83",
    product_original_price: "$274.00",
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 28242,
    product_url: "https://www.amazon.com/dp/B08PP5MSVB",
    product_photo:
      "https://m.media-amazon.com/images/I/51fYXSnSu9L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 48,
    product_minimum_offer_price: "$213.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery Wed, Jan 29 Or fastest delivery Tue, Jan 28",
    has_variations: true,
    product_badge: "Best Seller",
  },
  {
    asin: "B09SM24S8C",
    product_title:
      "Samsung Galaxy A03s Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 32GB, Long Lasting Battery, Expandable Storage, 3 Camera Lenses, Infinite Display - Black (Renewed)",
    product_price: "$72.00",
    product_original_price: "$99.99",
    currency: "USD",
    product_star_rating: "3.8",
    product_num_ratings: 934,
    product_url: "https://www.amazon.com/dp/B09SM24S8C",
    product_photo:
      "https://m.media-amazon.com/images/I/51m45B3Yy+L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 13,
    product_minimum_offer_price: "$51.59",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: true,
  },
  {
    asin: "B0C1Q3MVBP",
    product_title:
      "Samsung Galaxy A14 5G A Series, Factory Unlocked, 64GB, US Version, Black (Renewed)",
    product_price: "$98.33",
    product_original_price: "$168.00",
    currency: "USD",
    product_star_rating: "3.7",
    product_num_ratings: 1043,
    product_url: "https://www.amazon.com/dp/B0C1Q3MVBP",
    product_photo:
      "https://m.media-amazon.com/images/I/71L1ezoIH9L._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 22,
    product_minimum_offer_price: "$81.02",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: false,
  },
  {
    asin: "B00FRSYS12",
    product_title:
      "VTech CS6719-2 2-Handset Expandable Cordless Phone with Caller ID/Call Waiting, Handset Intercom &amp; Backlit Display/Keypad, Silver",
    product_price: "$38.95",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 38229,
    product_url: "https://www.amazon.com/dp/B00FRSYS12",
    product_photo:
      "https://m.media-amazon.com/images/I/71HLNfFVCcL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 26,
    product_minimum_offer_price: "$26.16",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: false,
  },
  {
    asin: "B0DLL7354W",
    product_title:
      "C24 | 2024 | All-Day Battery | GSM Unlocked | 5.5” Display | 2/16GB | 2300mAh | US Version | US Warranty | White",
    product_price: "$39.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.6",
    product_num_ratings: 68,
    product_url: "https://www.amazon.com/dp/B0DLL7354W",
    product_photo:
      "https://m.media-amazon.com/images/I/515cfOcCNyL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$39.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Fri, Jan 31 Or fastest delivery Tue, Jan 28",
    has_variations: false,
  },

  
];

export default data;
